language: ruby

before_install:
  - gem install bundler

bundler_args: --without development --jobs=3 --retry=3

cache: bundler

sudo: false

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-head
  - jruby-9.1.7.0

script:
  bundle exec rspec spec